### ISSUE TITLE
Utilização da rotina 

### ISSUE THREAD

**Issue by VictorAraujoVieira** [lucasbrustolin/Protheus-Etiqueta-Zebra#1]
Estou tentando utilizar seu fonte , mas da o seguinte erro :

THREAD ERROR ([50660], vieira.victor, SPOD2930)   07/07/2020 13:02:47
erro no parâmetroFWFormViewStruct: Campo:PDI_DESC não encontrado. on FWFORMMODELSTRUCT:SETPROPERTY(FWFORMMODELSTRUCT.PRX) 28/06/2019 18:27:43 line : 554

Tenha alguma ideia ?

**Comment by lucasbrustolin** [comment]
Vitor,

    Um outro analista teve o mesmo problema ao acessar o configurador quando ele fez o teste em uma base sem o dicionário no BD  o mesmo funcionou perfeitamente. Sugestão,  revise o dicionário de dados com os arquivos enviados.

De: Victor Araujo <notifications@github.com>
Enviada em: terça-feira, 7 de julho de 2020 13:04
Para: lucasbrustolin/Protheus-Etiqueta-Zebra <Protheus-Etiqueta-Zebra@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [lucasbrustolin/Protheus-Etiqueta-Zebra] Utilização da rotina (#1)


Estou tentando utilizar seu fonte , mas da o seguinte erro :

THREAD ERROR ([50660], vieira.victor, SPOD2930) 07/07/2020 13:02:47
erro no parâmetroFWFormViewStruct: Campo:PDI_DESC não encontrado. on FWFORMMODELSTRUCT:SETPROPERTY(FWFORMMODELSTRUCT.PRX) 28/06/2019 18:27:43 line : 554

Tenha alguma ideia ?

**Comment by VictorAraujoVieira** [comment]
Debuguei aqui , e percebi que o sistema não está carregando toda a estrutura da tabela , para cada estrutura 
oStruPDI
oStruPDI
oStruPDJ 

Só esta vindo o campo Filial, e quando você faz 

oStruPDI:SetProperty("PDI_DESC" , MODEL_FIELD_OBRIGAT, .T. )
oStruPDI:SetProperty("PDI_PORTA", MODEL_FIELD_OBRIGAT, .T. )
oStruPDJ:SetProperty("PDJ_TIPO" , MODEL_FIELD_OBRIGAT, .T. )

Da erro pois não encontra os campos 

Obs.: Dicionario no banco

**Comment by lucasbrustolin** [comment]
Sim,

   Como comentei, o problema está relacionado ao dicionário de dados.
   Me chame no Skype que te dou um help. https://join.skype.com/invite/ueWQ6m7iTuy7

De: Victor Araujo <notifications@github.com>
Enviada em: terça-feira, 7 de julho de 2020 13:30
Para: lucasbrustolin/Protheus-Etiqueta-Zebra <Protheus-Etiqueta-Zebra@noreply.github.com>
Cc: brustolin <lucasbrustolin@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [lucasbrustolin/Protheus-Etiqueta-Zebra] Utilização da rotina (#1)


Debuguei aqui , e percebi que o sistema não está carregando toda a estrutura da tabela , para cada estrutura
oStruPDI
oStruPDI
oStruPDJ

Só esta vindo o campo Filial, e quando você faz

oStruPDI:SetProperty("PDI_DESC" , MODEL_FIELD_OBRIGAT, .T. )
oStruPDI:SetProperty("PDI_PORTA", MODEL_FIELD_OBRIGAT, .T. )
oStruPDJ:SetProperty("PDJ_TIPO" , MODEL_FIELD_OBRIGAT, .T. )

Da erro pois não encontra os campos

Obs.: Dicionario no banco
